CONFIG = {
    "APP_NAME": "PyPad",
    "DEFAULT_WIDTH": 600,
    "DEFAULT_HEIGHT": 400,
    "MIN_APP_WINDOW_WIDTH": 300,
    "MIN_APP_WINDOW_HEIGHT": 200,
    "DEFAULT_NAME": "untitled",
    "DEFAULT_TITLE": "untitled - PyPad",
    "DEFAULT_FONT_SIZE": 12,
    "DEFAULT_FONT_FAMILY": "Consolas",
    "DEFAULT_BACKGROUND_COLOR": '#fff',
    "DEFAULT_FOREGROUND_COLOR": '#000',
    "DEFAULT_LINENUMBERINGAREA_BACKGROUND_COLOR": '#f0f0f0',
    "DEFAULT_LINENUMBERINGAREA_FOREGROUND_COLOR": '#aaa',
    "DEFAULT_FILETYPES": [
        ("Text file", '*.txt'), 
        ('All files', '*.*')
    ],
    "DEFAULT_HIGHLIGHTLINE_BACKGROUND": '#0078d7',
    "DEFAULT_HIGHLIGHTLINE_FOREGROUND": '#0078d7',
    "FIND_WINDOW_TITLE": 'Find',
    "REPLACE_WINDOW_TITLE": 'Find and Replace',
}